"""
Levisol Planning Tool — Excel report writer.
Detail sheets carry unit-rate columns and row-level cost FORMULAS, and the
Cost Summary sheet sums the detail sheets with formulas, so a planner who
hand-edits a volume sees costs recalculate.

Sheet layout after styling: row 1 = title, row 2 = blank, row 3 = headers,
data starts at row 4. All formulas are written AFTER the title rows are
inserted so cell references are final.
"""
import pandas as pd
from openpyxl.styles import Font, PatternFill, Alignment

HDR_FILL = PatternFill('solid', fgColor='1F4E33')
HDR_FONT = Font(name='Arial', bold=True, color='FFFFFF')
BODY_FONT = Font(name='Arial')
TITLE_FONT = Font(name='Arial', bold=True, size=14, color='1F4E33')
DATA_START = 4  # first data row after styling


def _style(ws, title):
    ws.insert_rows(1, 2)
    ws['A1'] = title
    ws['A1'].font = TITLE_FONT
    for c in range(1, ws.max_column + 1):
        cell = ws.cell(row=3, column=c)
        cell.fill, cell.font = HDR_FILL, HDR_FONT
        cell.alignment = Alignment(wrap_text=True, vertical='center')
        ws.column_dimensions[cell.column_letter].width = \
            max(14, min(28, len(str(cell.value or '')) + 4))
    for row in ws.iter_rows(min_row=DATA_START):
        for cell in row:
            cell.font = BODY_FONT
    ws.freeze_panes = f'A{DATA_START}'


def _cost_col(wb, ws_name, col_idx, header, formula_fn, nrows):
    ws = wb[ws_name]
    h = ws.cell(row=3, column=col_idx, value=header)
    h.fill, h.font = HDR_FILL, HDR_FONT
    h.alignment = Alignment(wrap_text=True, vertical='center')
    ws.column_dimensions[h.column_letter].width = 16
    for r in range(DATA_START, DATA_START + nrows):
        cell = ws.cell(row=r, column=col_idx, value=formula_fn(r))
        cell.font = BODY_FONT
        cell.number_format = '#,##0'


def write_report(path, data, cfa_norms, hub_norms, res, params):
    prod = res['production'].copy()
    prod['Unit cost (₹/kL)'] = prod['Plant'].map(data['prod_cost'])
    ph = res['plant_hub'].copy()
    ph['Rate (₹/kL)'] = ph.apply(lambda r: data['plant_hub_cost'][(r['Plant'], r['Hub'])], axis=1)
    hc = res['hub_cfa'].copy()
    hc['Rate (₹/kL)'] = hc.apply(lambda r: data['hub_cfa_cost'][(r['Hub'], r['CFA'])], axis=1)
    un = res['unmet'].copy()
    if len(un):
        un['Tier'] = un['SKU'].map(data['tier'])
        un['Contractual'] = un['SKU'].map(data['sku_contract']).map({True: 'Yes', False: 'No'})
        un['Penalty rate (₹/kL)'] = un.apply(
            lambda r: data['sku_penalty'][r['SKU']] *
            (params['contractual_multiplier'] if r['Contractual'] == 'Yes' else 1.0), axis=1)
    else:
        un = pd.DataFrame(columns=['SKU', 'CFA', 'Unmet (kL)', 'Tier', 'Contractual',
                                   'Penalty rate (₹/kL)'])
    hub_end = res['hub_ending'].copy()

    with pd.ExcelWriter(path, engine='openpyxl') as xw:
        readme = pd.DataFrame({'Levisol Monthly Planning Output': [
            'Generated by the deterministic planning engine (norms + exact MILP).',
            f"Solver status: {res['mip_status']}",
            f"CFA end-of-month stock target: {params['cfa_stock_target']}",
            f"Contractual unmet multiplier: {params['contractual_multiplier']}x",
            f"Hub SS shortfall cost: Rs {params['hub_shortfall_cost']:,.0f}/kL",
            f"Hub SS requirement scale: {params.get('hub_ss_scale', 1.0)}x",
            'Cost Summary totals are live formulas over the detail sheets.',
            'Batch size: 25 kL. 30 working days per month.',
        ]})
        readme.to_excel(xw, sheet_name='README', index=False)
        cfa_norms.to_excel(xw, sheet_name='Norms - CFA', index=False)
        hub_norms.to_excel(xw, sheet_name='Norms - Hub', index=False)
        prod.to_excel(xw, sheet_name='Production Plan', index=False)
        ph.to_excel(xw, sheet_name='Routing Plant-Hub', index=False)
        hc.to_excel(xw, sheet_name='Routing Hub-CFA', index=False)
        un.to_excel(xw, sheet_name='Unmet Demand', index=False)
        hub_end.to_excel(xw, sheet_name='Hub Stock Position', index=False)
        res['net_req'].to_excel(xw, sheet_name='CFA Net Requirement', index=False)

        wb = xw.book
        titles = {
            'Norms - CFA': 'Inventory Norms — per SKU × CFA',
            'Norms - Hub': 'Inventory Norms — per SKU × Hub',
            'Production Plan': 'Production Plan — Jan 2026 (25 kL batches)',
            'Routing Plant-Hub': 'Routing — Plant to Hub',
            'Routing Hub-CFA': 'Routing — Hub to CFA',
            'Unmet Demand': 'Unmet Demand (deliberate, priced under-service)',
            'Hub Stock Position': 'Hub Stock Position vs Safety-Stock Norm',
            'CFA Net Requirement': 'CFA Net Requirement = Jan forecast + stock target − opening',
        }
        for name, title in titles.items():
            _style(wb[name], title)

        # row-level cost formulas (written after styling; data starts at row 4)
        _cost_col(wb, 'Production Plan', 6, 'Cost (₹)', lambda r: f'=D{r}*E{r}', len(prod))
        _cost_col(wb, 'Routing Plant-Hub', 6, 'Cost (₹)', lambda r: f'=D{r}*E{r}', len(ph))
        _cost_col(wb, 'Routing Hub-CFA', 6, 'Cost (₹)', lambda r: f'=D{r}*E{r}', len(hc))
        _cost_col(wb, 'Unmet Demand', 7, 'Penalty (₹)', lambda r: f'=C{r}*F{r}', len(un))

        last = DATA_START - 1
        ws = wb.create_sheet('Cost Summary')
        rows = [
            ('Production',
             f"=SUM('Production Plan'!F{DATA_START}:F{last+len(prod)})" if len(prod) else 0),
            ('Plant→Hub freight',
             f"=SUM('Routing Plant-Hub'!F{DATA_START}:F{last+len(ph)})" if len(ph) else 0),
            ('Hub→CFA freight',
             f"=SUM('Routing Hub-CFA'!F{DATA_START}:F{last+len(hc)})" if len(hc) else 0),
            ('Unmet-demand penalty',
             f"=SUM('Unmet Demand'!G{DATA_START}:G{last+len(un)})" if len(un) else 0),
            ('Hub SS shortfall penalty',
             f"=SUMIF('Hub Stock Position'!H{DATA_START}:H{last+len(hub_end)},"
             f'">0")*{params["hub_shortfall_cost"]}' if len(hub_end) else 0),
        ]
        ws['A1'] = 'Cost head'
        ws['B1'] = '₹'
        for i, (k, v) in enumerate(rows, start=2):
            ws.cell(row=i, column=1, value=k)
            ws.cell(row=i, column=2, value=v)
        tot_row = len(rows) + 2
        ws.cell(row=tot_row, column=1, value='TOTAL')
        ws.cell(row=tot_row, column=2, value=f'=SUM(B2:B{len(rows)+1})')
        for r in range(1, tot_row + 1):
            bold = r in (1, tot_row)
            ws.cell(row=r, column=1).font = Font(name='Arial', bold=bold)
            c2 = ws.cell(row=r, column=2)
            c2.font = Font(name='Arial', bold=bold)
            c2.number_format = '#,##0'
        ws.column_dimensions['A'].width = 30
        ws.column_dimensions['B'].width = 18
